# Draw keymap diagrams using keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - 'config/*.keymap'
      - 'config/includes/*.dtsi'
      - keymap-drawer/keymap_drawer.config.yaml
      - .github/workflows/keymap-drawer.yml
permissions:
  contents: write

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      keymap_patterns: 'config/*.keymap'
      config_path: keymap-drawer/keymap_drawer.config.yaml
      output_folder: keymap-drawer
      install_branch: main
      amend_commit: true
      json_path: keymap-drawer/layouts
